USUARIO_INDEX = "usuario_index"
USUARIO_UPDATE = "usuario_update"
USUARIO_SHOW = "usuario_show"
USUARIO_NEW = "usuario_new"
USUARIO_DESTROY = "usuario_destroy"

PUNTO_INDEX = "punto_index"
PUNTO_UPDATE = "punto_update"
PUNTO_SHOW = "punto_show"
PUNTO_NEW = "punto_new"
PUNTO_DESTROY = "punto_destroy"

DENUNCIA_INDEX = "denuncia_index"
DENUNCIA_UPDATE = "denuncia_update"
DENUNCIA_SHOW = "denuncia_show"
DENUNCIA_NEW = "denuncia_new"
DENUNCIA_DESTROY = "denuncia_destroy"

ZONAS_INDEX = "zonas_index"
ZONAS_UPDATE = "zonas_update"
ZONAS_SHOW = "zonas_show"
ZONAS_NEW = "zonas_new"
ZONAS_DESTROY = "zonas_destroy"

RECORRIDOS_INDEX = "recorridos_index"
RECORRIDOS_UPDATE = "recorridos_update"
RECORRIDOS_SHOW = "recorridos_show"
RECORRIDOS_NEW = "recorridos_new"
RECORRIDOS_DESTROY = "recorridos_destroy"